name: Publish to npm (reusable)
on:
  workflow_call:
    inputs:
      workingdir:
        type: string
        default: './'
      environment:
        type: string
        default: 'npm'
      dry-run:
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read # Required for repository checkout
      id-token: write # Required for OIDC
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
         persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # 5.0.0
        with:
          node-version: 24
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ inputs.workingdir }}
      - name: Publish to npm
        if: ${{ !inputs.dry-run }}
        run: npm publish --access public
        working-directory: ${{ inputs.workingdir }}

